"""Add configurable_agents and agent_execution_logs tables

Revision ID: a1b2c3d4e5f6
Revises: 9596c6d44bfa
Create Date: 2026-01-19 22:23:19.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9596c6d44bfa'
branch_labels = None
depends_on = None

# Note: 0001_init est une ancienne migration qui crée des tables en conflit
# avec le nouveau système. Elle est ignorée et n'est pas dans la chaîne de migration.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurable_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('markdown_config', sa.Text(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('mcp_servers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_configurable_agents_id'), 'configurable_agents', ['id'], unique=False)
    op.create_index(op.f('ix_configurable_agents_name'), 'configurable_agents', ['name'], unique=False)
    op.create_index(op.f('ix_configurable_agents_slug'), 'configurable_agents', ['slug'], unique=True)
    op.create_index(op.f('ix_configurable_agents_user_id'), 'configurable_agents', ['user_id'], unique=False)
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('output_raw', sa.Text(), nullable=True),
    sa.Column('output_parsed', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['configurable_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_agent_id'), 'agent_execution_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_user_id'), 'agent_execution_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_execution_logs_user_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    op.drop_index(op.f('ix_configurable_agents_user_id'), table_name='configurable_agents')
    op.drop_index(op.f('ix_configurable_agents_slug'), table_name='configurable_agents')
    op.drop_index(op.f('ix_configurable_agents_name'), table_name='configurable_agents')
    op.drop_index(op.f('ix_configurable_agents_id'), table_name='configurable_agents')
    op.drop_table('configurable_agents')
    # ### end Alembic commands ###
